name: Deploy to Render when develop is merged to main

on:
  push:
    branches: [main]
  pull_request:
    branches:
        - main
jobs:
  # Define a job named "ci"
  ci:
    # Specify the operating system to run the job on
    runs-on: ubuntu-latest
    
    # Define the steps to be executed in the job
    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v3

      # Define a step named "Test"
      - name: Test
        # Run install and test scripts
        run: |
            npm install
            npm run test-gui

      # Define a step named "Deploy"
      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        # Set an environment variable with the deployment URL from secrets
        env:
          DEPLOY_URL: ${https://api.render.com/deploy/srv-cv8e07rqf0us73b764og?key=hIu5XS2xVFo}
        # Run the deployment command
        run: |
          curl "$DEPLOY_URL"
