name: Run Tests on Pull Request to develop

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

# what does checkout@v2 means
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js 21.x
        uses: actions/setup-node@v2
        with:
          node-version: 21.x  
          
      - name: Install dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Run tests
        run: npm run test-component